version: '3'
volumes:
  postgres_data:
    driver: local
services:
  postgres:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
  keycloak:
    container_name: keycloak-app
    restart: always
    depends_on:
      - postgres
    image: quay.io/keycloak/keycloak:22.0.5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      DB_SCHEMA: public
      KC_FEATURES: preview
    command: 
      - start-dev 
    ports:
      - 8080:8080
